package com.abs.backend.exception;

public enum ErrorCode {

    INSUFFICIENT_STOCK,
    PRODUCT_NOT_FOUND,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    ORDER_NOT_EDITABLE,
    UNAUTHORIZED_ACTION,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    CART_ITEM_NOT_FOUND,
    UNAUTHORIZED,
    CATEGORY_NOT_FOUND
}