spring:
  datasource:
    url: jdbc:postgresql://db.hodcnzcdjrsjwriumrrd.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Dheeran1212#

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG